foreground   #e3e4c8
background   #1d1310
cursor       #e3e4c8

color0       #1d1310
color8       #9e9f8c
color1       #986128
color9       #986128
color2       #A36E3D
color10      #A36E3D
color3       #728B58
color11      #728B58
color4       #9F9961
color12      #9F9961
color5       #D6AF45
color13      #D6AF45
color6       #B4BA91
color14      #B4BA91
color7       #e3e4c8
color15      #e3e4c8
