# Shell variables
# Generated by 'wal'
wallpaper='/home/joaorossi/Pictures/wallhaven-k7z71q.jpg'

# Special
background='#1d1310'
foreground='#e3e4c8'
cursor='#e3e4c8'

# Colors
color0='#1d1310'
color1='#986128'
color2='#A36E3D'
color3='#728B58'
color4='#9F9961'
color5='#D6AF45'
color6='#B4BA91'
color7='#e3e4c8'
color8='#9e9f8c'
color9='#986128'
color10='#A36E3D'
color11='#728B58'
color12='#9F9961'
color13='#D6AF45'
color14='#B4BA91'
color15='#e3e4c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
