conky.config = {
  --====================  (mesmas definições iniciais)  ====================
  alignment = 'top_left',
  gap_x = 30,
  gap_y = 50,
  maximum_width = 330,
  minimum_height = 700,
  minimum_width = 330,

  use_xft = true,
  override_utf8_locale = true,
  font = 'DepartureMono Nerd Font Mono:light:size=9',

  default_color = '7f5a60',
  color1 = '6a0e1e',
  color2 = '7f5a60',

  background = false,
  border_width = 1,
  draw_borders = false,
  draw_graph_borders = false,
  draw_outline = false,
  draw_shades = false,
  own_window = true,
  own_window_colour = '63452C',
  own_window_class = 'Conky',
  own_window_argb_visual = true,
  own_window_type = 'desktop',
  own_window_transparent = true,
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  stippled_borders = 0,

}

conky.text = [[
${offset 14}${voffset 35}${color1}${font PxPlus IBM VGA 8x16:bold:size=18}Weekly Routine${font}
${offset 14}${voffset 5}${color}${font DepartureMono Nerd Font Mono:bold:size=10}     14h–16h  | 16h–18h${font}
${offset 14}${voffset 4}${font DepartureMono Nerd Font Mono:bold:size=12}${color1}Seg: ${color}LR    | LR
${offset 14}${voffset 2}${color1}Ter: ${color}LR    | LR
${offset 14}${voffset 2}${color1}Qua: ${color}LR    | LR
${offset 14}${voffset 2}${color1}Qui: ${color}LR    | LR
${offset 14}${voffset 2}${color1}Sex: ${color}CLASS | CLASS
${offset 14}${voffset 2}${color1}Sab: ${color}OFF   | OFF
${offset 14}${voffset 2}${color1}Dom: ${color}CLASS | CLASS${font}
]]

