;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝

;==========================================================
;==========================================================

include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/colors.ini

[bar/i3_bar]
height = 21pt
radius = 2
dpi = 100

background = ${custom-red-theme.background}
foreground = ${custom-red-theme.foreground}
line-size = 0pt
border-size = 2pt
border-color = ${custom-red-theme.arcana}
module-margin = 0
padding-left = 7pt
padding-right = 7pt
separator = "|  "
separator-foreground = ${custom-red-theme.accent}

width    = 50%
offset-x = 25%
offset-y = 0.5%

font-0      = "DepartureMono Nerd Font Mono:style=Bold:size=9"
;font-0      = "PxPlus IBM VGA 8x16:style=Bold:size=9"

modules-left = wsc 
;modules-left = wsc tray
;
modules-right = filesystem temp pulseaudio battery time 
cursor-click = pointer
;cursor-scroll = ns-resize
enable-ipc = true
wm-restack = i3
